In [1]:
# Import the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [ ]:
# Download and load the cifar10 data
(train_images, train_labels), (test_images, test_labels) = (
    tf.keras.datasets.cifar10.load_data()
)

In [ ]:
def normalize_img(image, label):
    return tf.cast(image, tf.float32) / 255.0, label

In [ ]:
train_images, train_labels = normalize_img(train_images, train_labels)
test_images, test_labels = normalize_img(test_images, test_labels)

In [ ]:
train_images[0:2]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[0.23137255, 0.24313726, 0.24705882],
         [0.16862746, 0.18039216, 0.1764706 ],
         [0.19607843, 0.1882353 , 0.16862746],
         ...,
         [0.61960787, 0.5176471 , 0.42352942],
         [0.59607846, 0.49019608, 0.4       ],
         [0.5803922 , 0.4862745 , 0.40392157]],

        [[0.0627451 , 0.07843138, 0.07843138],
         [0.        , 0.        , 0.        ],
         [0.07058824, 0.03137255, 0.        ],
         ...,
         [0.48235294, 0.34509805, 0.21568628],
         [0.46666667, 0.3254902 , 0.19607843],
         [0.47843137, 0.34117648, 0.22352941]],

        [[0.09803922, 0.09411765, 0.08235294],
         [0.0627451 , 0.02745098, 0.        ],
         [0.19215687, 0.10588235, 0.03137255],
         ...,
         [0.4627451 , 0.32941177, 0.19607843],
         [0.47058824, 0.32941177, 0.19607843],
         [0.42745098, 0.28627452, 0.16470589]],

        ...,

        [[0.8156863 , 0.6666667 , 0.

In [2]:
# Download and load the cifar10 data
(train_images, train_labels), (test_images, test_labels) = (
    tf.keras.datasets.cifar10.load_data()
)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step


In [3]:
def normalize_img(image, label):
    return tf.cast(image, tf.float32) / 255.0, label

In [4]:
train_images, train_labels = normalize_img(train_images, train_labels)
test_images, test_labels = normalize_img(test_images, test_labels)

In [5]:
train_images[0:2]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[0.23137255, 0.24313726, 0.24705882],
         [0.16862746, 0.18039216, 0.1764706 ],
         [0.19607843, 0.1882353 , 0.16862746],
         ...,
         [0.61960787, 0.5176471 , 0.42352942],
         [0.59607846, 0.49019608, 0.4       ],
         [0.5803922 , 0.4862745 , 0.40392157]],

        [[0.0627451 , 0.07843138, 0.07843138],
         [0.        , 0.        , 0.        ],
         [0.07058824, 0.03137255, 0.        ],
         ...,
         [0.48235294, 0.34509805, 0.21568628],
         [0.46666667, 0.3254902 , 0.19607843],
         [0.47843137, 0.34117648, 0.22352941]],

        [[0.09803922, 0.09411765, 0.08235294],
         [0.0627451 , 0.02745098, 0.        ],
         [0.19215687, 0.10588235, 0.03137255],
         ...,
         [0.4627451 , 0.32941177, 0.19607843],
         [0.47058824, 0.32941177, 0.19607843],
         [0.42745098, 0.28627452, 0.16470589]],

        ...,

        [[0.8156863 , 0.6666667 , 0.

## ResNet Block


#### Without `dropout`


In [6]:
class ResBlock(tf.keras.layers.Layer):
    def __init__(self, num_filters, dropout=0.0):
        super(ResBlock, self).__init__()

        self.cnn1 = tf.keras.layers.Conv2D(
            num_filters,
            kernel_size=(3, 3),
            padding="same",
            activation="relu",
            kernel_initializer="he_uniform",
        )

        self.cnn2 = tf.keras.layers.Conv2D(
            num_filters,
            kernel_size=(3, 3),
            padding="same",
            kernel_initializer="he_uniform",
        )  # No activation here

        self.activation = tf.keras.layers.ReLU()

    def call(self, inputs, training=False):
        x = self.cnn1(inputs)

        x = self.cnn2(x)

        # Residual connection
        x += inputs  # Skip connection

        out = self.activation(x) # Apply ReLU after addition
        
        return out

#### With `dropout`


In [7]:
class ResBlock(tf.keras.layers.Layer):
    def __init__(self, num_filters, dropout=0.0):
        super(ResBlock, self).__init__()

        self.cnn1 = tf.keras.layers.Conv2D(
            num_filters,
            kernel_size=(3, 3),
            padding="same",
            activation="relu",
            kernel_initializer="he_uniform",
        )
        self.dropout1 = tf.keras.layers.Dropout(dropout) if dropout > 0 else None

        self.cnn2 = tf.keras.layers.Conv2D(
            num_filters,
            kernel_size=(3, 3),
            padding="same",
            kernel_initializer="he_uniform",
        )  # No activation here
        self.dropout2 = tf.keras.layers.Dropout(dropout) if dropout > 0 else None

        self.activation = tf.keras.layers.ReLU()

    def call(self, inputs, training=False):
        x = self.cnn1(inputs)
        if self.dropout1:
            x = self.dropout1(x, training=training)

        x = self.cnn2(x)
        if self.dropout2:
            x = self.dropout2(x, training=training)

        # Residual connection
        x += inputs  # Skip connection

        return self.activation(x)  # Apply ReLU after addition

In [13]:


class ResBlock(tf.keras.layers.Layer):
    def __init__(self, num_filters, dropout_rate=0.0):
        super(ResBlock, self).__init__()

        self.cnn1 = tf.keras.layers.Conv2D(num_filters, (3, 3), padding='same', activation='relu')
        self.dropout1 = tf.keras.layers.Dropout(dropout_rate)

        self.cnn2 = tf.keras.layers.Conv2D(num_filters, (3, 3), padding='same')
        self.dropout2 = tf.keras.layers.Dropout(dropout_rate)

        # 1x1 Conv to match input channels if necessary
        self.shortcut = tf.keras.layers.Conv2D(num_filters, (1, 1), padding='same')

        self.activation = tf.keras.layers.ReLU()

    def call(self, inputs, training=False):
        shortcut = self.shortcut(inputs)  # Ensure input shape matches output shape

        x = self.cnn1(inputs)
        x = self.dropout1(x, training=training)  # Apply dropout during training

        x = self.cnn2(x)
        x = self.dropout2(x, training=training)  # Apply dropout during training

        x += shortcut  # Add residual connection
        return self.activation(x)


In [14]:
from sklearn import metrics


in_layer = tf.keras.layers.Input(shape=(32,32,3,))

# 3 Resnet blocks with dropout (30%)
b = ResBlock(32, 0.3)(in_layer)
b = ResBlock(64, 0.3)(b)
b = ResBlock(128, 0.3)(b)

b = tf.keras.layers.Flatten()(b)
b = tf.keras.layers.Dense(128, activation='relu')(b)
b = tf.keras.layers.Dropout(0.4)(b)
out_layer = tf.keras.layers.Dense(10, activation='softmax')(b)

model = tf.keras.Model(in_layer, out_layer)
model.summary()

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 32, 32, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ res_block_3 (ResBlock)          │ (None, 32, 32, 32)     │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ res_block_4 (ResBlock)          │ (None, 32, 32, 64)     │        57,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ res_block_5 (ResBlock)          │ (None, 32, 32, 128)    │       229,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 131072)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │    16,777,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,076,202 (65.14 MB)

 Trainable params: 17,076,202 (65.14 MB)

 Non-trainable params: 0 (0.00 B)